/* Code generated by cbindgen. DO NOT EDIT. */

#ifndef RUST_C_FILE_SYSTEM_H
#define RUST_C_FILE_SYSTEM_H



#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>
#ifdef __cplusplus
extern "C" {
#endif

typedef struct DirIter DirIter;

typedef struct WatcherHandle WatcherHandle;

typedef struct RNStats {
  uint64_t dev;
  uint64_t ino;
  uint32_t mode;
  uint64_t nlink;
  uint32_t uid;
  uint32_t gid;
  uint64_t rdev;
  uint64_t size;
  uint64_t blksize;
  uint64_t blocks;
  double atime_ms;
  double mtime_ms;
  double ctime_ms;
  double birthtime_ms;
} RNStats;

typedef struct RNIovec {
  uint8_t *base;
  size_t len;
} RNIovec;

typedef void (*WatchCallback)(void*, const char*, int32_t);

int rn_fs_access(const char *path, int mode);

int rn_fs_truncate(const char *path, size_t len);

int rn_fs_ftruncate(int fd, size_t len);

int rn_fs_fsync(int fd);

int rn_fs_chmod(const char *path, int mode);

int rn_fs_fchmod(int fd, int mode);

int rn_fs_chown(const char *path, int uid, int gid);

int rn_fs_fchown(int fd, int uid, int gid);

int rn_fs_utimes(const char *path, double atime, double mtime);

int rn_fs_futimes(int fd, double atime, double mtime);

int rn_fs_stat(const char *path, struct RNStats *out);

int rn_fs_lstat(const char *path, struct RNStats *out);

int rn_fs_fstat(int fd, struct RNStats *out);

bool rn_fs_mkdir(const char *path, uint32_t mode, bool recursive);

int rn_fs_rmdir(const char *path);

int rn_fs_unlink(const char *path);

int rn_fs_rename(const char *old_path, const char *new_path);

int rn_fs_copy_file(const char *src, const char *dest, int _flags);

int rn_fs_link(const char *existing, const char *new_path);

int rn_fs_symlink(const char *target, const char *path);

char *rn_fs_readlink(const char *path);

char *rn_fs_realpath(const char *path);

struct DirIter *rn_fs_readdir_open(const char *path);

char *rn_fs_readdir_next(struct DirIter *iter_ptr);

void rn_fs_free_string(char *s);

void rn_fs_readdir_close(struct DirIter *iter_ptr);

char *rn_fs_mkdtemp(const char *prefix);

int rn_fs_rm(const char *path, bool recursive);

uint8_t *rn_fs_read_file(const char *path, size_t *out_len);

void rn_fs_read_file_free(uint8_t *ptr, size_t len);

int rn_fs_write_file(const char *path, const uint8_t *data, size_t len);

int rn_fs_open(const char *path, int flags, int _mode);

int rn_fs_close(int fd);

int rn_fs_read(int fd, uint8_t *buffer, size_t len, int position);

int rn_fs_write(int fd, const uint8_t *buffer, size_t len, int position);

char *rn_fs_get_temp_dir(void);

int rn_fs_lchown(const char *path, uint32_t uid, uint32_t gid);

int rn_fs_lutimes(const char *path, int64_t atime_sec, int64_t mtime_sec);

int rn_fs_lchmod(const char *path, uint32_t mode);

intptr_t rn_fs_readv(int fd, const struct RNIovec *iovecs, int iovcnt, int64_t position);

intptr_t rn_fs_writev(int fd, const struct RNIovec *iovecs, int iovcnt, int64_t position);

struct WatcherHandle *rn_fs_watch(const char *path, void *context, WatchCallback callback);

void rn_fs_unwatch(struct WatcherHandle *handle);

#ifdef __cplusplus
}
#endif

#endif /* RUST_C_FILE_SYSTEM_H */
